export const GameMetadata = { 
    "Nessie": { "element": "cryptozoologic-nessie", "orientation" : "portrait" },
    "Pukwudgie": { "element": "cryptozoologic-pukwudgie", "orientation" : "portrait" },
    "Shempscape": { "element": "cryptozoologic-shempscape", "orientation" : "portrait" },
    "Mothman": { "element": "cryptozoologic-mothman", "orientation" : "portrait" },
    "Irish Yeti": { "element": "cryptozoologic-irish-yeti", "orientation" : "portrait" },
    "Ozark Howler": { "element": "cryptozoologic-ozark-howler", "orientation" : "portrait" },
    "Bessie": { "element": "cryptozoologic-bessie", "orientation" : "portrait" },
    "Tessie": { "element": "cryptozoologic-tessie", "orientation" : "portrait" },
    "Fluxly": { "element": "cryptozoologic-fluxly", "orientation" : "portrait" },
    "Yak Shaver": { "element": "cryptozoologic-yak-shaver", "orientation" : "portrait" },
    "Whumpus": { "element": "cryptozoologic-whumpus", "orientation" : "portrait" },
    "Batsquatch": { "element": "cryptozoologic-batsquatch", "orientation" : "portrait" },
    "Beast of Cardiff": { "element": "cryptozoologic-beast-of-cardiff", "orientation" : "portrait" },
    "Donut Beast": { "element": "cryptozoologic-donut-beast", "orientation" : "portrait" },
    "Jersey Devil": { "element": "cryptozoologic-jersey-devil", "orientation" : "portrait" },
    "Lizard Man": { "element": "cryptozoologic-lizard-man", "orientation" : "portrait" },
    "Montauk Monster": { "element": "cryptozoologic-montauk-monster", "orientation" : "portrait" },
    "Murray": { "element": "cryptozoologic-murray", "orientation" : "portrait" },
    "Mograh": { "element": "cryptozoologic-mograh", "orientation" : "portrait" },
    "Gorrog": { "element": "cryptozoologic-gorrog", "orientation" : "portrait" },
    "Snake Scarecrow": { "element": "cryptozoologic-snake-scarecrow", "orientation" : "portrait" },
    "Vampire Unicorn": { "element": "cryptozoologic-vampire-unicorn", "orientation" : "portrait" },
    "Pyrahua": { "element": "cryptozoologic-pyrahua", "orientation" : "portrait" },
    "Vivian Ghastly": { "element": "cryptozoologic-vivian-ghastly", "orientation" : "portrait" },
    "Spark Boa": { "element": "cryptozoologic-spark-boa", "orientation" : "portrait" },
    "Smoke Crow": { "element": "cryptozoologic-smoke-crow", "orientation" : "portrait" },
    "Beast of Baz": { "element": "cryptozoologic-beast-of-baz", "orientation" : "portrait" },
    "Ningen": { "element": "cryptozoologic-ningen", "orientation" : "portrait" },
    "Yowie": { "element": "cryptozoologic-yowie", "orientation" : "portrait" },
    "Dark Thunderbird": { "element": "cryptozoologic-dark-thunderbird", "orientation" : "portrait" },
    "Ogopogo": { "element": "cryptozoologic-ogopogo", "orientation" : "portrait" }
}