#! /bin/bash
echo ${PD:-pd}

${PD:-pd} ${PDSETTINGS:-} \
    -path ${BASEDIR:-.} -path ${BASEDIR:-.}/lib -path ${BASEDIR:-.}/../../lib \
    -path ${BASEDIR:-.}/../../sound/loops \
    -rt \
    -channels 6 -audiobuf 15 \
    $* ${BASEDIR:-.}/loops.pd
